export const userTypes = {
    HANDLE_LOGIN: 'HANDLE_LOGIN',
    HANDLE_LOGOUT: 'HANDLE_LOGOUT',
    FETCH_USER_REQUEST: 'FETCH_USER_REQUEST',
    FETCH_USER_SUCCESS: 'FETCH_USER_SUCCESS',
    FETCH_USER_FAILURE: 'FETCH_USER_FAILURE',
    HANDLE_USERNAME: 'HANDLE_USERNAME'
}

export const productsTypes = {
    FETCH_ALL_PRODUCTS: 'FETCH_ALL_PRODUCTS',
    FETCH_PRODUCTS_FAILURE: 'FETCH_PRODUCTS_FAILURE',
    SLICED_PRODUCTS: 'SLICED_PRODUCTS',
}

export const productType = {
    FETCH_PRODUCT: 'FETCH_PRODUCT',
    FETCH_PRODUCT_FAILURE: 'FETCH_PRODUCT__FAILURE'
}

